title: ShiweiShang 的个人主页
description: "欢迎来到我的个人主页和博客"
baseurl: ""
url: "https://ShiweiShang.github.io"

theme: minima

author:
  name: ShiweiShang
  email: your@email.com

# 博客文章目录
collections:
  posts:
    output: true

# 导航栏
nav:
  - title: 博客
    url: /
  - title: 关于我
    url: /about.html

# 其他设置
markdown: kramdown
highlighter: rouge